# 新しいウィンドウのベース番号
set-option -g base-index 1

# すべてのベルを無視
set-option -g bell-action none

# 256色端末を使用する
set-option -g default-terminal "screen-256color"

# viのキーバインドを使用する
set-window-option -g mode-keys vi

# クリップボード共有
set-option -g default-command "~/.tmux/tmux-MacOSX-pasteboard/reattach-to-user-namespace -l $SHELL"
bind-key C-c run "tmux save-buffer - | ~/.tmux/tmux-MacOSX-pasteboard/reattach-to-user-namespace pbcopy"
bind-key C-v run "~/.tmux/tmux-MacOSX-pasteboard/reattach-to-user-namespace pbpaste | tmux load-buffer - && tmux paste-buffer"

# ステータスバー
set-option -g status-fg cyan
set-option -g status-bg black
set-option -g status-left-length 30
set -g status-left '#[fg=colour252,bg=colour238,nobold]>>#[fg=white,bg=colour238,bold] #(whoami) #[fg=colour238,bg=colour234,nobold]>>'
set-option -g status-right '#[fg=magenta,bg=black,bold] #(echo $LANG) #[fg=colour238,bg=colour234,nobold]<<#[fg=colour252,bg=colour238,nobold] %Y-%m-%d(%a) %H:%M #[default]#[fg=colour252,bg=colour238,nobold]<<'
set-window-option -g window-status-current-fg cyan
set-window-option -g window-status-current-bg black
set-window-option -g window-status-current-attr bold#,underscore

