# prefixキーをC-aに変更する
set -g prefix C-a

# C-bのキーバインドを解除する
unbind C-b

# キーストロークのディレイを減らす
set -s escape-time 1

# ウィンドウのインデックスを1から始める
set -g base-index 1

# ペインのインデックスを1から始める
setw -g pane-base-index 1

# 設定ファイルをリロードする
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# C-a*2でtmux内のプログラムにC-aを送る
bind C-a send-prefix

# | でペインを縦に分割する
bind | split-window -h
# - でペインを横に分割する
bind - split-window -v
# \ でカレントディレクトリのままペインを縦に分割する
bind \ split-window -h -c "#{pane_current_path}"
# _ でカレントディレクトリのままペインを横に分割する
bind _ split-window -v -c "#{pane_current_path}"

# Vimのキーバインドでペインを移動する
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

# Vimのキーバインドでペインをリサイズする
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# マウス操作を無効にする
setw -g mouse off

# 256色端末を使用する
set -g default-terminal "screen-256color"

# ステータスバーの色を設定する
set -g status-style fg=white,bg=black

# ウィンドウリストの色を設定する
setw -g window-style fg=cyan,bg=black
# アクティブなウィンドウを目立たせる
setw -g window-status-current-style fg=white,bold,bg=red

# ペインボーダーの色を設定する
# setw -g pane-border-style fg=green,bg=black
# アクティブなペインを目立たせる
# setw -g pane-active-border-style fg=white,bg=yellow
# アクティブなペイン以外をシェードアウトする
# setw -g window-style fg=colour240,bg=colour235
setw -g window-active-style fg=white,bg=black

# コマンドラインの色を設定する
set -g message-style fg=white,bold,bg=black

# ステータスバーを設定する
## 左パネルを設定する
set -g status-left-length 40
set -g status-left "#[fg=green]Session: #S #[fg=yellow]#I #[fg=cyan]#P"
## 右パネルを設定する
set -g status-right "#[fg=cyan][%Y-%m-%d(%a) %H:%M]"
## リフレッシュの間隔を設定する(デフォルト 15秒)
set -g status-interval 60
## ウィンドウリストの位置を中心寄せにする
set -g status-justify centre
## ヴィジュアルノーティフィケーションを有効にする
setw -g monitor-activity on
set -g visual-activity on
## ステータスバーを上部に表示する
set -g status-position top

# コピーモードを設定する
## viのキーバインドを使用する
setw -g mode-keys vi
## コピーモードの操作をvi風に設定する
bind Escape copy-mode
bind -T copy-mode-vi 'v' send -X begin-selection
bind -T copy-mode-vi 'y' send -X copy-selection
unbind p
bind p paste-buffer
## クリップボード共有を有効にする(macOS)
set -g default-command "reattach-to-user-namespace -l zsh"
bind C-c run "tmux save-buffer - | reattach-to-user-namespace pbcopy"
bind -T copy-mode-vi y send -X copy-pipe "reattach-to-user-namespace pbcopy"
bind C-v run "tmux set-buffer \"$(reattach-to-user-namespace pbpaste)\"; tmux paste-buffer"

# 全てのペインで一斉に同じコマンドを実行する
bind C-s set-window-option synchronize-panes
